[versions]
google-gms-google-services = "4.5.0"
firebase-auth = "24.2.0"
credentials = "1.6.0"
credentials-play-services-auth = "1.6.0"
googleid = "1.2.0"

[libraries]
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebase-auth" }
credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials-play-services-auth" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

[plugins]
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "google-gms-google-services" }

